### PR TITLE
WIP: hack archive/tar to prevent having to read entries in memory

### PR DESCRIPTION
**Pull request by oliverpool**
Following the conversation with @mholt at https://github.com/caddyserver/caddy/issues/4945 and https://github.com/mholt/archiver/issues/323.

To expose a tar as a http.FileSystem, it needs to support `Seek`. This repo currently reads all the entries in memory (#4): https://github.com/nlepage/go-tarfs/blob/bec76bb13b0a3be9e1bf8bb03141a6d26ce91902/fs.go#L39-L44

I wanted to try another way and here is what I managed to achieve:
1. copy the current stdlib `archive/tar` as a `tar` package https://github.com/nlepage/go-tarfs/commit/0f59c8705ff4a868f2265cf6f18586535ad37780
2. add a `SectionReader` interface and method to expose the underlying file with a `Seek` method (`hack.go` file inside the `tar` package: https://github.com/nlepage/go-tarfs/commit/e77dab3bb990cad5e1dc7d1eb3f6c56fc08a6e9c#diff-57148db3d25f4f7ecf8bf6a8c57b98f408490d0ccf8e625b832db5afd66d165e)
3. use this method to make a `fs.FS` ( `hack_fs.go`)
4. profit!

My goal was to make as few modifications to the stdlib, to maybe have it integrated upstream (currently adding 1 interface and 1 method).

The work is still incomplete:
- if a `Read` happens on the archived file before `SectionReader` is called, the already read bytes will be missing from the `SectionReader`
- the `*sparseFileReader` is not supported

Let me know what you think!

### CODE REVIEW

**Comment by nlepage** [comment]
Hi @oliverpool 
This is definitely something that would be nice to have. 
Right now I'm on vacation 🩴 so I can't have a look at the code, but I'll be able to in a few days.

**Comment by oliverpool** [comment]
I completed the work:
- calling `Read` before retrieving the `SectionReader` shouldn't be an issue anymore
- `*sparseFileReader` is now supported

It now needs to be properly tested (I am not really confident about the implementation of `*sparseFileReader` ^^)

**Comment by mholt** [comment]
Oh hey, so I tweeted this cause I think it's cool, and [in the replies](https://twitter.com/bradfitz/status/1557752304891150337) I was linked to a library by Brad Fitzpatrick that does something similar: https://pkg.go.dev/golang.org/x/build/crfs/stargz -- requires writing it in a special way though.

**Comment by oliverpool** [comment]
@mholt thanks for the input!
`stargz` looks very interesting, even if the scope is a bit different:
- it tries to read only the needed portions of the archive (because it is accessed over the network)
- in my case, the .tar file is local, so I don't care reading the whole file once at startup (to gather a "table of content")
- **having the entries gzipped makes it challenging to have the underlying file seekable (needed for `http.FileSystem`)**

---

Go code that I found around the (e)stargz it (I couldn't find any `fs.FS` implementation - which will need to support seeking!):
- https://github.com/google/crfs 
> Stargz's format is: `Gzip(TarF(file1)) + Gzip(TarF(file2)) + Gzip(TarF(file3_chunk1)) + Gzip(F(file3_chunk2)) + Gzip(F(index of earlier files in magic file), TarFooter)`, where the trailing ZIP-like index contains offsets for each file/chunk's GZIP header in the overall **stargz** file.

- https://pkg.go.dev/github.com/containerd/stargz-snapshotter/estargz
- https://github.com/containerd/stargz-snapshotter/blob/main/docs/estargz.md

**Comment by nlepage** [comment]
Hey @oliverpool, I've finally had the time to take a look at the PR.

This is really nice, I didn't know about `SectionReader`, which is a really cool feature!

However, having a hacked copy of `archive/tar` doesn't seem reasonnable to me (maintainability, compatibility with different go versions).

This gave me an idea to use `SectionReader` to create a new `tar.Reader` for each file read, here is what I managed to do so  far : #14 
The major drawback is [having to rebuild an `io.Seeker` over the `tar.Reader`](https://github.com/nlepage/go-tarfs/pull/14/commits/8b9763039cf5b9a73bcf460773a0d25d87cd064c#diff-33f8fbc61d6878200e61e69725cd724475a0c9dbb73bc63fcfc913a5651764feR132).
For now I stored the file content in memory while it is read, which allows to perform seeks backward later on...
I think we could avoid storing the file content in memory, by discarding the skipped content in case of forward seeks, and recreating a new `tar.Reader` in case of backward seeks...

Let me know what you think about it.

**Comment by oliverpool** [comment]
> having a hacked copy of archive/tar doesn't seem reasonnable to me

I totally agree. I was wondering, if the `hack.go` could be integrated in the standard library (`SectionReader` interface and method). Hence this experiment.

Thinking more about it, for  "one-file-FS", the `cbd` format might be more appropriate:
- http://cr.yp.to/cdb.html
- https://github.com/jbarham/cdb
- https://github.com/colinmarc/cdb

**Comment by nlepage** [comment]
Hi @oliverpool 
I wanted to let you know that we have ongoing work at #14 and #16 to solve this without hacking the archive/tar package.

**Comment by oliverpool** [comment]
Thanks for the heads up. My usecase is actually to plug this into an `http.FS` without holding the whole file in memory (if I understand correctly, your PR is about disabling seeking if asked upon creation - which would not work in my case).

**Comment by joelanford** [comment]
My DisableSeek commit in #16 is opt-in, to reduce memory usage. I don't need http.FS for my use case, so I am looking for a way to avoid allocating memory unnecessarily when opening a file within the tar FS.

It may still be possible to avoid memory allocations without hacking archive/tar, but at a minimum, it seems reimplementing sparse tar support would be necessary.

**Comment by oliverpool** [comment]
I have been experimenting with another way which seems very promising: fake the `Seek` calls.

The http layer only seeks in very specific occasions:
- to guess the MIME: back to start after reading 512 bytes
- to satisfy the `range` requests

I have developed a package to buffer the first 512 bytes and re-read them on request:
https://git.sr.ht/~oliverpool/exp/tree/main/item/seekfaker/seekfaker.go

It works as long as the internal of the http don't change significantly, but looks more elegant!

**Comment by oliverpool** [comment]
I made a proposal to the Go team to eventually integrate this workaround in the stdlib: https://github.com/golang/go/issues/61791

**Comment by nlepage** [comment]
@oliverpool @mholt Closing this PR as the new version [v1.2.0](https://github.com/nlepage/go-tarfs/releases/tag/v1.2.0) avoids reading entries content in memory (without hacking in the stdlib), as long as the `io.Reader` given to `tarfs.New` implements `io.ReaderAt`.

Regarding the `io.Seeker` implementation (for usage with `http.FS`), an actual `io.Seeker` (not a fake one) is implemented on top of the `tar.Reader`, so this is also OK.

Let me know if this new version feets your needs.

**Comment by mholt** [comment]
@nlepage That sounds perfect! (Right?)

I'd have to try it out but ReaderAt should be available for regular OS files; that's my primary use case. (Serving tar files from disk.)

I probably won't have time to try this soon, unfortunately, (I mean, making a file system module for Caddy where the files are read from a tar file on disk), but anyone else is welcome to of course!

Super exciting!! Thank you!

**Pull request closed without merging**
