### PR TITLE
🐛fix tfs.Stat failed on "."

### PR DESCRIPTION
**Pull request by ix64**

### CODE REVIEW

**Comment by nlepage** [comment]
Hi @ix64 
Thank you for your contributions 🙏 
I have setup builds for go1.17 and windows to validate your previous pull requests.
Could you add a test for this one ?
Thank you

**Review by nlepage — APPROVED** [review]

**Comment by nlepage** [comment]
I added a test 🙂 
Thank you!
I'll publish a new release shortly.

**Comment by nlepage** [comment]
New release published https://github.com/nlepage/go-tarfs/releases/tag/v1.0.5

**Comment by ix64** [comment]
Sorry for the late response.


> New release published https://github.com/nlepage/go-tarfs/releases/tag/v1.0.5

Great! Thanks for your work!

**Pull request merged**
